work

diff --git a/Dockerfile-backend b/Dockerfile-backend
--- a/Dockerfile-backend
+++ b/Dockerfile-backend
@@ -5,11 +5,15 @@
 
 # https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact
 
-FROM php:7.4-fpm as php
+FROM php:7.4-fpm as php_development
+
+ENV COMPOSER_ALLOW_SUPERUSER=1
+COPY --from=composer /usr/bin/composer /usr/bin/composer
 
 # required packages and PHP extensionns
-RUN apt-get -y update \
-    && apt-get -y install git \
+RUN set -eux ; \
+    apt-get -y update; \
+    apt-get -y --no-install-recommends install git  \
         zip \
         unzip \
         curl \
@@ -20,47 +24,39 @@ RUN apt-get -y update \
         libicu-dev \
         graphviz \
         acl \
-        libfcgi-bin \
-    && docker-php-ext-install -j$(nproc) \
+        libfcgi-bin ; \
+    apt-get clean ; \
+    rm -rf /var/lib/apt/lists/* ; \
+    docker-php-ext-install -j$(nproc) \
     pdo  \
     pdo_pgsql \
     intl \
-    pcntl \
-    && pecl install amqp \
-    && docker-php-ext-enable amqp \
-    && docker-php-ext-enable opcache
+    pcntl ; \
+    pecl install amqp ; \
+    pecl install xdebug; \
+    docker-php-ext-enable amqp ; \
+    docker-php-ext-enable opcache ; \
+    docker-php-ext-enable xdebug ; \
+    echo "xdebug.remote_enable = 1" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini; \
+    echo "xdebug.remote_connect_back = 1" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
 
-COPY config/php/docker-entrypoint.sh /usr/local/bin/docker-entrypoint
-RUN chmod +x /usr/local/bin/docker-entrypoint
+COPY ./config/php/docker-entrypoint.sh /usr/local/bin/docker-entrypoint
+COPY ./config/php/php-fpm.d/zzz-01-healthcheck.conf /usr/local/etc/php-fpm.d/zzz-01-healthcheck.conf
+COPY ./config/php/php-fpm-healthcheck.sh /usr/local/bin/php-fpm-healthcheck
+COPY ./config/php/override.ini /usr/local/etc/php/conf.d/override.ini
 
-#HEALTHCHECK
-ADD ./config/php/php-fpm.d/zzz-01-healthcheck.conf /usr/local/etc/php-fpm.d/zzz-01-healthcheck.conf
-ADD ./config/php/php-fpm-healthcheck.sh /usr/local/bin/php-fpm-healthcheck
-RUN chmod 755 /usr/local/bin/php-fpm-healthcheck
+
+# install Symfony Flex globally to speed up download of Composer packages (parallelized prefetching) \
+RUN set -eux ; \
+    chmod +x /usr/local/bin/docker-entrypoint; \
+    chmod 755 /usr/local/bin/php-fpm-healthcheck ; \
+    composer --ansi --version --no-interaction; \
+    composer global require "symfony/flex" --prefer-dist --no-progress --no-suggest --classmap-authoritative; \
+	composer clear-cache;
 
 HEALTHCHECK --start-period=5m  CMD php-fpm-healthcheck
-
-ADD ./config/php/override.ini /usr/local/etc/php/conf.d/override.ini
-
-# Composer
-ENV COMPOSER_ALLOW_SUPERUSER=1
-COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
-RUN composer --ansi --version --no-interaction
-
-# install Symfony Flex globally to speed up download of Composer packages (parallelized prefetching)
-RUN set -eux; \
-	composer global require "symfony/flex" --prefer-dist --no-progress --no-suggest --classmap-authoritative; \
-	composer clear-cache
-
 ENTRYPOINT ["docker-entrypoint"]
 CMD ["php-fpm"]
-
-FROM php as php_development
-
-RUN pecl install xdebug \
-    && docker-php-ext-enable xdebug \
-    && echo "xdebug.remote_enable = 1" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
-    && echo "xdebug.remote_connect_back = 1" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
 
 WORKDIR /srv/app
 
@@ -80,6 +76,7 @@ COPY  backend/composer.json \
 
 RUN set -eux; \
 	composer install --prefer-dist --no-autoloader --no-scripts --no-progress --no-suggest; \
+	mkdir -p config/jwt var/cache var/log import public/multimedia; \
 	composer clear-cache
 
 COPY backend/bin bin/
@@ -90,23 +87,26 @@ COPY backend/src src/
 COPY backend/templates templates/
 COPY backend/translations translations/
 
+#clean up
 RUN set -eux; \
-	mkdir -p config/jwt var/cache var/log import public/multimedia; \
+    chmod +x bin/console; \
 	composer dump-autoload --optimize; \
+	composer dump-env prod; \
     composer run-script post-install-cmd; \
-	chmod +x bin/console; sync
-
-RUN bin/console cache:clear --env=prod --no-debug
-
-RUN rm -rf /tmp/*  && apt-get clean
-
-FROM php_development as php_final_with_xdebug
+	bin/console cache:clear --env=prod --no-debug ; \
+	bin/console cache:clear --env=dev ; \
+	rm -rf /tmp/* ; \
+    # remove unnecessary dev packages
+    apt-get purge -y "*-dev" ; \
+    apt-get autoremove -y  ; \
+    php --version ; \
+    sync
 
 FROM php_development as php_production
-
-#clean up
-# do not use .env  in production
-RUN composer dump-env prod; \
+	# do not use .env  in production
+RUN set -eux; \
+    pecl uninstall xdebug ; \
+    rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini; \
 	rm -f .env \
      .env.test \
      *.dist \
@@ -115,35 +115,36 @@ RUN composer dump-env prod; \
      depfile.yml \
      config/jwt/*.pem \
      tests \
-     features
+     features ; \
+     sync
 
-RUN pecl uninstall xdebug && rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
-
-# remove unnecessary dev packages
-RUN apt-get purge -y "*-dev" && apt-get autoremove -y && apt-get clean
 
 FROM nginx:1.17 AS nginx
 
-RUN apt-get update && apt-get install -y \
-    curl iputils-ping \
-    && apt-get clean
+RUN  set -eux; \
+    apt-get update ; \
+    apt-get --no-install-recommends install -y \
+    curl \
+    iputils-ping; \
+    apt-get clean; \
+    rm -rf /var/lib/apt/lists/* ; \
+    rm -rf /tmp/*
 
 FROM nginx as nginx_development
 
-ADD ./config/nginx/conf.d/symfony-development.conf.template /etc/nginx/conf.d/symfony-development.conf.template
-ADD ./config/nginx/nginx.conf /etc/nginx/nginx.conf
+COPY ./config/nginx/conf.d/symfony-development.conf.template /etc/nginx/conf.d/symfony-development.conf.template
+COPY ./config/nginx/nginx.conf /etc/nginx/nginx.conf
+COPY ./config/nginx/docker-entrypoint.sh /usr/local/bin/docker-entrypoint
 
-ADD ./config/nginx/docker-entrypoint.sh /usr/local/bin/docker-entrypoint
 RUN chmod +x /usr/local/bin/docker-entrypoint
 
 HEALTHCHECK --start-period=5m CMD curl --fail http://localhost/api/doc || exit 1
-
 ENTRYPOINT ["docker-entrypoint"]
 
 CMD ["nginx", "-g", "daemon off;"]
 
 FROM nginx_development as nginx_production
 
-ADD ./config/nginx/conf.d/symfony-production.conf.template /etc/nginx/conf.d/symfony-production.conf.template
+COPY ./config/nginx/conf.d/symfony-production.conf.template /etc/nginx/conf.d/symfony-production.conf.template
 
 COPY --from=php_production /srv/app/public /srv/app/public
diff --git a/Dockerfile-node b/Dockerfile-node
--- a/Dockerfile-node
+++ b/Dockerfile-node
@@ -2,7 +2,10 @@
 FROM node:12.6 as node
 
 COPY config/node/docker-entrypoint.sh /usr/local/bin/docker-entrypoint
-RUN chmod +x /usr/local/bin/docker-entrypoint
+RUN  set -eux; \
+    chmod +x /usr/local/bin/docker-entrypoint ; \
+    #We have installed curl?
+    curl --version
 
 ENTRYPOINT ["docker-entrypoint"]
 
@@ -17,23 +20,24 @@ ENV PORT=80
 
 CMD ["npm", "run", "dev"]
 
-COPY frontend /srv/app/
-RUN npm install && npm run build
-
 FROM node_development as node_production
+
 WORKDIR /srv/app
-#clean up
-# do not use .env /  test files in production
-RUN rm -f .env*
+
+COPY frontend /srv/app/
+RUN  set -eux; \
+    npm install ; \
+    npm run build ; \
+    #clean up
+    rm -f .env*
 
 CMD ["npm", "run", "start"]
 
-FROM node as docs
+FROM node as docs_development
+
 RUN npm install docsify-cli -g
 
 HEALTHCHECK --start-period=5m CMD curl --fail http://localhost:3000 || exit 1
 
 CMD ["docsify", "serve" ,"docs"]
-
-FROM docs as docs_final
 
